"""VLM-Guided Motion Planner for ErovoutikaGrab.

Integrates YOLOE detections (coordinates, bounding box, segmentation polygon, readings)
with local Vision-Language Model (VLM / Ollama) reasoning and deterministic kinematic guards
to plan safe robot approach movements that eliminate overshoot and stiction deadband.
"""

import json
import logging
import math
import os
import threading
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from src.core.events import DetectionResult

logger = logging.getLogger(__name__)


@dataclass
class VLMMotionPlan:
    """Structured motion and servo arm grab plan generated by VLM and kinematic planner."""
    action: str  # "DRIVE_FORWARD", "PIVOT_LEFT", "PIVOT_RIGHT", "NUDGE_FORWARD", "NUDGE_BACK", "NUDGE_LEFT", "NUDGE_RIGHT", "ALIGNED_GRASP", "STOP"
    recommended_pwm: int = 230  # Clamped >= min_overcoming_pwm
    duration_ms: int = 250  # Pulse duration for micro-nudges
    damping_factor: float = 1.0  # Speed scaling factor (0.5 to 1.0) to prevent overshoot
    base_speed: int = 230  # Baseline speed from robot config
    overshoot_risk: str = "LOW"  # "LOW", "MEDIUM", "HIGH"
    stiction_risk: str = "LOW"  # "LOW", "MEDIUM", "HIGH"
    alignment_status: str = "CENTERED"  # "CENTERED", "NEEDS_LEFT", "NEEDS_RIGHT"
    horizontal_error_px: int = 0  # dx = cx - sweet_x
    area_ratio: float = 0.0  # bbox_area / sweet_spot_area
    target_is_moving: bool = False  # True if target is dynamically moving in view
    movement_mode: str = "SMOOTH_FAST"  # "SMOOTH_FAST" (stationary target) or "SMOOTH_PULSE" (moving target)
    left_pwm: int = 0  # Planned left wheel PWM
    right_pwm: int = 0  # Planned right wheel PWM
    path_type: str = "CONTINUOUS_APPROACH"  # "CONTINUOUS_APPROACH", "ARC_ALIGN", "PIVOT_ALIGN", "HOLD_STANDOFF", "REVERSE_CLEAR", "STOP"
    is_overextended: bool = False  # True if target is closer than safe standoff distance (prevents over-extending)
    continuous_drive: bool = False  # True when robot cruises continuously along the planned efficient path
    distance_cm: float = 0.0
    target_dist_cm: float = 0.0
    target_info: Dict[str, Any] = field(default_factory=dict)
    arm_plan: Dict[str, Any] = field(default_factory=dict)  # Servo arm trajectory & calibrated grab sequence
    rationale: str = ""
    source: str = "VLM_HYBRID"  # "VLM_OLLAMA" or "VLM_KINEMATIC"
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action,
            "recommended_pwm": self.recommended_pwm,
            "left_pwm": self.left_pwm,
            "right_pwm": self.right_pwm,
            "duration_ms": self.duration_ms,
            "damping_factor": round(self.damping_factor, 2),
            "base_speed": self.base_speed,
            "overshoot_risk": self.overshoot_risk,
            "stiction_risk": self.stiction_risk,
            "alignment_status": self.alignment_status,
            "horizontal_error_px": self.horizontal_error_px,
            "area_ratio": round(self.area_ratio, 3),
            "target_is_moving": self.target_is_moving,
            "movement_mode": self.movement_mode,
            "path_type": self.path_type,
            "is_overextended": self.is_overextended,
            "continuous_drive": self.continuous_drive,
            "distance_cm": round(self.distance_cm, 1),
            "target_dist_cm": round(self.target_dist_cm, 1),
            "target_info": self.target_info,
            "arm_plan": self.arm_plan,
            "rationale": self.rationale,
            "source": self.source,
            "timestamp": self.timestamp
        }


class VLMMotionPlanner:
    """High-level trajectory planner combining YOLOE readings with local VLM reasoning and calibrated servo arm kinematics."""

    def __init__(
        self,
        ollama_url: str = "http://localhost:11434",
        vlm_model: str = "moondream:latest",
        min_overcoming_pwm: int = 230,
        base_speed: int = 230,
        turn_speed: int = 228,
        nudge_pwm: int = 245,
        nudge_default_ms: int = 250,
        max_speed: int = 255,
        align_tol_x: int = 20,
        pulse_threshold_px: int = 45,
        s1_stow: int = 93,
        s1_down: int = 170,
        s1_min: int = 60,
        s1_max: int = 170,
        s1_center: int = 93,
        s2_stow: int = 45,
        s2_down: int = 0,
        s2_min: int = 0,
        s2_max: int = 45,
        s2_center: int = 45,
        s3_open: int = 170,
        s3_close: int = 40,
        s3_min: int = 40,
        s3_max: int = 170,
        s3_center: int = 170,
        step_deg: int = 2,
        step_delay_s: float = 0.02,
        servos_cfg: Optional[Dict[str, Any]] = None
    ):
        self.ollama_url = ollama_url.rstrip("/")
        self.vlm_model = vlm_model
        self.min_overcoming_pwm = min_overcoming_pwm
        self.base_speed = base_speed
        self.turn_speed = turn_speed
        self.nudge_pwm = nudge_pwm
        self.nudge_default_ms = nudge_default_ms
        self.max_speed = max_speed
        self.align_tol_x = align_tol_x
        self.pulse_threshold_px = pulse_threshold_px

        # Calibrated Servo Arm Kinematics from robot_config.yaml
        self.s1_stow: int = s1_stow
        self.s1_down: int = s1_down
        self.s1_min: int = s1_min
        self.s1_max: int = s1_max
        self.s1_center: int = s1_center

        self.s2_stow: int = s2_stow
        self.s2_down: int = s2_down
        self.s2_min: int = s2_min
        self.s2_max: int = s2_max
        self.s2_center: int = s2_center

        self.s3_open: int = s3_open
        self.s3_close: int = s3_close
        self.s3_min: int = s3_min
        self.s3_max: int = s3_max
        self.s3_center: int = s3_center

        self.step_deg: int = step_deg
        self.step_delay_s: float = step_delay_s

        if servos_cfg:
            self._parse_servos_cfg(servos_cfg)

        self._last_plan: Optional[VLMMotionPlan] = None
        self._lock = threading.Lock()
        self._planning_in_progress = False

        # VLM Continuous Learning & Dynamic Adaptation State
        self.adaptive_stiction_boost: int = 0
        self.adaptive_damping_scale: float = 1.0
        self.pulse_duration_scale: float = 1.0
        self.total_plans_generated: int = 0
        self.total_plans_executed: int = 0
        self.overshoots_prevented: int = 0
        self.stiction_recoveries: int = 0
        self.recent_history: List[Dict[str, Any]] = []
        base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
        self.adaptation_log_path = os.path.join(base_dir, "logs", "vlm_adaptation_log.jsonl")

    def _parse_servos_cfg(self, servos_cfg: dict):
        """Extracts calibrated servo angles from nested YAML or flat dictionary."""
        if not isinstance(servos_cfg, dict):
            return

        s1 = servos_cfg.get("servo1_shoulder", {})
        s2 = servos_cfg.get("servo2_elbow", {})
        s3 = servos_cfg.get("servo3_gripper", {})

        # S1 (Shoulder)
        if "stow_angle" in s1: self.s1_stow = int(s1["stow_angle"])
        elif "s1_stow" in servos_cfg: self.s1_stow = int(servos_cfg["s1_stow"])
        if "down_angle" in s1: self.s1_down = int(s1["down_angle"])
        elif "s1_down" in servos_cfg: self.s1_down = int(servos_cfg["s1_down"])
        if "min_angle" in s1: self.s1_min = int(s1["min_angle"])
        elif "s1_min" in servos_cfg: self.s1_min = int(servos_cfg["s1_min"])
        if "max_angle" in s1: self.s1_max = int(s1["max_angle"])
        elif "s1_max" in servos_cfg: self.s1_max = int(servos_cfg["s1_max"])
        if "center_angle" in s1: self.s1_center = int(s1["center_angle"])
        elif "s1_center" in servos_cfg: self.s1_center = int(servos_cfg["s1_center"])

        # S2 (Elbow)
        if "stow_angle" in s2: self.s2_stow = int(s2["stow_angle"])
        elif "s2_stow" in servos_cfg: self.s2_stow = int(servos_cfg["s2_stow"])
        if "down_angle" in s2: self.s2_down = int(s2["down_angle"])
        elif "s2_down" in servos_cfg: self.s2_down = int(servos_cfg["s2_down"])
        if "min_angle" in s2: self.s2_min = int(s2["min_angle"])
        elif "s2_min" in servos_cfg: self.s2_min = int(servos_cfg["s2_min"])
        if "max_angle" in s2: self.s2_max = int(s2["max_angle"])
        elif "s2_max" in servos_cfg: self.s2_max = int(servos_cfg["s2_max"])
        if "center_angle" in s2: self.s2_center = int(s2["center_angle"])
        elif "s2_center" in servos_cfg: self.s2_center = int(servos_cfg["s2_center"])

        # S3 (Gripper)
        if "open_angle" in s3: self.s3_open = int(s3["open_angle"])
        elif "s3_open" in servos_cfg: self.s3_open = int(servos_cfg["s3_open"])
        if "close_angle" in s3: self.s3_close = int(s3["close_angle"])
        elif "s3_close" in servos_cfg: self.s3_close = int(servos_cfg["s3_close"])
        if "min_angle" in s3: self.s3_min = int(s3["min_angle"])
        elif "s3_min" in servos_cfg: self.s3_min = int(servos_cfg["s3_min"])
        if "max_angle" in s3: self.s3_max = int(s3["max_angle"])
        elif "s3_max" in servos_cfg: self.s3_max = int(servos_cfg["s3_max"])
        if "center_angle" in s3: self.s3_center = int(s3["center_angle"])
        elif "s3_center" in servos_cfg: self.s3_center = int(servos_cfg["s3_center"])

        if "step_deg" in servos_cfg: self.step_deg = int(servos_cfg["step_deg"])
        if "step_delay_s" in servos_cfg: self.step_delay_s = float(servos_cfg["step_delay_s"])

    def reload_config(self, motors_cfg: dict = None, vision_cfg: dict = None, servos_cfg: dict = None):
        """Dynamically update kinematics, sweet spot calibration, and servo arm limits."""
        with self._lock:
            if motors_cfg and isinstance(motors_cfg, dict):
                if "min_overcoming_pwm" in motors_cfg:
                    self.min_overcoming_pwm = int(motors_cfg["min_overcoming_pwm"])
                if "base_speed" in motors_cfg:
                    self.base_speed = int(motors_cfg["base_speed"])
                if "turn_speed" in motors_cfg:
                    self.turn_speed = int(motors_cfg["turn_speed"])
                if "nudge_pwm" in motors_cfg:
                    self.nudge_pwm = int(motors_cfg["nudge_pwm"])
                if "nudge_default_ms" in motors_cfg:
                    self.nudge_default_ms = int(motors_cfg["nudge_default_ms"])
                if "max_speed" in motors_cfg:
                    self.max_speed = int(motors_cfg["max_speed"])

                # Check if servos were nested inside motors_cfg (e.g. whole robot_config passed)
                if "servos" in motors_cfg and not servos_cfg:
                    self._parse_servos_cfg(motors_cfg["servos"])

            if vision_cfg and isinstance(vision_cfg, dict) and "grasp_sweet_spot" in vision_cfg:
                sp = vision_cfg["grasp_sweet_spot"]
                if "align_tolerance_x" in sp:
                    self.align_tol_x = int(sp["align_tolerance_x"])

            if servos_cfg:
                self._parse_servos_cfg(servos_cfg)

    def plan_movement(
        self,
        detection: Optional[DetectionResult],
        sweet_spot: Dict[str, int],
        use_vlm_llm: bool = True,
        vlm_timeout_s: float = 3.0,
        target_is_moving: bool = False,
        dist_cm: Optional[float] = None,
        target_dist_cm: Optional[float] = None
    ) -> VLMMotionPlan:
        """Computes safe motion and servo arm grab plan from YOLOE detection, coordinates, and segmentation."""
        if not detection or not detection.detected:
            arm_plan = self._compute_arm_plan(
                action="STOP",
                category="NONE",
                box_w=0,
                sweet_w=sweet_spot.get("box_width", 196),
                area_ratio=0.0,
                is_centered=False
            )
            plan = VLMMotionPlan(
                action="STOP",
                recommended_pwm=0,
                duration_ms=0,
                damping_factor=1.0,
                base_speed=self.base_speed,
                overshoot_risk="LOW",
                stiction_risk="LOW",
                alignment_status="UNKNOWN",
                target_is_moving=False,
                movement_mode="STOP",
                left_pwm=0,
                right_pwm=0,
                path_type="STOP",
                is_overextended=False,
                continuous_drive=False,
                distance_cm=0.0,
                target_dist_cm=0.0,
                arm_plan=arm_plan,
                rationale="No target detected by vision model. Motors and arm halted in safe stowed state.",
                source="VLM_KINEMATIC"
            )
            with self._lock:
                self.total_plans_generated += 1
                self._last_plan = plan
            return plan

        # 1. Extract exact geometric metrics
        ymin, xmin, ymax, xmax = detection.bounding_box
        box_w = max(1, xmax - xmin)
        box_h = max(1, ymax - ymin)
        box_area = box_w * box_h

        cx, cy = detection.center
        sx = sweet_spot.get("center_x", 324)
        sy = sweet_spot.get("center_y", 247)
        sw = sweet_spot.get("box_width", 196)
        sh = sweet_spot.get("box_height", 157)
        sweet_area = max(1, sw * sh)

        # Metrics
        dx = cx - sx  # Positive: target is to the right
        area_ratio = box_area / sweet_area
        mask_poly = getattr(detection, "mask_polygon", None)
        mask_pts_count = len(mask_poly) if mask_poly else 0
        mask_area = getattr(detection, "mask_area", box_area)

        # 2. Physics-Based Kinematic Motion Plan & Arm Grasp Plan (Deterministic Guard)
        kinematic_plan = self._compute_kinematic_plan(
            dx=dx,
            area_ratio=area_ratio,
            category=detection.category,
            confidence=detection.confidence,
            color=detection.material_color,
            mask_pts_count=mask_pts_count,
            coords=(ymin, xmin, ymax, xmax, cx, cy, sx, sy, sw, sh),
            target_is_moving=target_is_moving,
            dist_cm=dist_cm,
            target_dist_cm=target_dist_cm
        )

        # 3. Optional local VLM augmentation (if enabled and fast response possible)
        if use_vlm_llm:
            try:
                vlm_augmented = self._query_vlm_reasoner(
                    detection=detection,
                    dx=dx,
                    area_ratio=area_ratio,
                    mask_pts_count=mask_pts_count,
                    sweet_spot=sweet_spot,
                    kinematic_baseline=kinematic_plan,
                    timeout_s=vlm_timeout_s
                )
                if vlm_augmented:
                    kinematic_plan = vlm_augmented
            except Exception as e:
                logger.debug(f"[VLMPlanner] Ollama query bypassed or timed out: {e}")

        with self._lock:
            self.total_plans_generated += 1
            self._last_plan = kinematic_plan
        return kinematic_plan

    def _compute_arm_plan(
        self,
        action: str,
        category: str,
        box_w: int,
        sweet_w: int,
        area_ratio: float,
        is_centered: bool
    ) -> Dict[str, Any]:
        """Plans servo arm trajectory and adaptive grip angle based on robot config calibration."""
        s3_min_bound = min(self.s3_min, self.s3_max)
        s3_max_bound = max(self.s3_min, self.s3_max)

        # Compute adaptive grip angle based on object width relative to sweet spot width
        norm_w = min(1.0, max(0.05, float(box_w) / max(1, sweet_w)))
        gripper_span = self.s3_open - self.s3_close
        adaptive_close = int(self.s3_close + gripper_span * (norm_w * 0.18))
        adaptive_close = max(s3_min_bound, min(s3_max_bound, adaptive_close))

        calibrated_angles = {
            "s1_stow": self.s1_stow,
            "s1_down": self.s1_down,
            "s1_min": self.s1_min,
            "s1_max": self.s1_max,
            "s2_stow": self.s2_stow,
            "s2_down": self.s2_down,
            "s2_min": self.s2_min,
            "s2_max": self.s2_max,
            "s3_open": self.s3_open,
            "s3_close": self.s3_close,
            "s3_min": self.s3_min,
            "s3_max": self.s3_max,
            "grip_target": adaptive_close,
            "step_deg": self.step_deg,
            "step_delay_s": self.step_delay_s
        }

        if action == "ALIGNED_GRASP":
            trajectory = [
                {
                    "stage": 1,
                    "name": "PRE_OPEN_JAWS",
                    "s1": self.s1_stow,
                    "s2": self.s2_stow,
                    "s3": self.s3_open,
                    "duration_s": 0.4,
                    "description": f"Pre-open gripper to calibrated {self.s3_open}° while holding upright pose."
                },
                {
                    "stage": 2,
                    "name": "LOWER_TO_TARGET",
                    "s1": self.s1_down,
                    "s2": self.s2_down,
                    "s3": self.s3_open,
                    "duration_s": 1.0,
                    "description": f"Lower shoulder to {self.s1_down}° and elbow to {self.s2_down}° into ground pick zone."
                },
                {
                    "stage": 3,
                    "name": "CLAMP_GRIPPER",
                    "s1": self.s1_down,
                    "s2": self.s2_down,
                    "s3": adaptive_close,
                    "duration_s": 0.7,
                    "description": f"Firmly clamp {category} with gripper at {adaptive_close}° (calibrated close {self.s3_close}°)."
                },
                {
                    "stage": 4,
                    "name": "LIFT_AND_STOW",
                    "s1": self.s1_stow,
                    "s2": self.s2_stow,
                    "s3": adaptive_close,
                    "duration_s": 1.0,
                    "description": f"Lift arm with grasped {category} to upright stow pose (S1={self.s1_stow}°, S2={self.s2_stow}°)."
                }
            ]
            return {
                "arm_action": "EXECUTE_GRAB",
                "grasp_readiness": "READY",
                "calibrated_angles": calibrated_angles,
                "trajectory": trajectory,
                "total_duration_s": round(sum(s["duration_s"] for s in trajectory), 2),
                "summary": f"Arm ready to grasp {category} using calibrated angles (S1:{self.s1_down}°, S2:{self.s2_down}°, S3:{adaptive_close}°)."
            }

        elif action in ("DRIVE_FORWARD", "NUDGE_FORWARD"):
            trajectory = [
                {
                    "stage": 1,
                    "name": "STOW_PRE_OPEN",
                    "s1": self.s1_stow,
                    "s2": self.s2_stow,
                    "s3": self.s3_open,
                    "duration_s": 0.3,
                    "description": f"Maintain upright stow pose (S1={self.s1_stow}°, S2={self.s2_stow}°) with gripper pre-opened to {self.s3_open}°."
                }
            ]
            return {
                "arm_action": "PREPARE_APPROACH",
                "grasp_readiness": "APPROACHING",
                "calibrated_angles": calibrated_angles,
                "trajectory": trajectory,
                "total_duration_s": 0.3,
                "summary": f"Arm holding stow pose ({self.s1_stow}°, {self.s2_stow}°) while chassis approaches target."
            }

        elif action in ("PIVOT_LEFT", "PIVOT_RIGHT", "NUDGE_LEFT", "NUDGE_RIGHT"):
            return {
                "arm_action": "HOLD_ALIGNING",
                "grasp_readiness": "ALIGNING",
                "calibrated_angles": calibrated_angles,
                "trajectory": [],
                "total_duration_s": 0.0,
                "summary": f"Arm tucked in stow pose ({self.s1_stow}°, {self.s2_stow}°) during chassis heading alignment."
            }

        elif action == "NUDGE_BACK":
            return {
                "arm_action": "HOLD_CLEARANCE",
                "grasp_readiness": "OVERSHOT",
                "calibrated_angles": calibrated_angles,
                "trajectory": [],
                "total_duration_s": 0.0,
                "summary": f"Arm stowed ({self.s1_stow}°, {self.s2_stow}°) while reversing to restore pick clearance."
            }

        else:
            return {
                "arm_action": "HOLD_STOW",
                "grasp_readiness": "NO_TARGET",
                "calibrated_angles": calibrated_angles,
                "trajectory": [],
                "total_duration_s": 0.0,
                "summary": "Motors and arm halted in safe stowed state."
            }

    def _compute_kinematic_plan(
        self,
        dx: int,
        area_ratio: float,
        category: str,
        confidence: float,
        color: str,
        mask_pts_count: int,
        coords: Tuple[int, ...],
        target_is_moving: bool = False,
        dist_cm: Optional[float] = None,
        target_dist_cm: Optional[float] = None
    ) -> VLMMotionPlan:
        """Calculates deterministic safe motion plan, continuous efficient path, and calibrated arm grab sequence."""
        ymin, xmin, ymax, xmax, cx, cy, sx, sy, *rest = coords
        sw = rest[0] if len(rest) > 0 else 196
        sh = rest[1] if len(rest) > 1 else 157
        box_w = max(1, xmax - xmin)

        target_info = {
            "category": category,
            "confidence": round(confidence, 2),
            "color": color,
            "centroid": [cx, cy],
            "bbox": [ymin, xmin, ymax, xmax],
            "dx_px": dx,
            "area_ratio_pct": round(area_ratio * 100, 1),
            "segmentation_points": mask_pts_count,
            "target_is_moving": target_is_moving
        }

        # Check Horizontal Alignment
        is_centered = abs(dx) <= self.align_tol_x
        align_status = "CENTERED" if is_centered else ("NEEDS_RIGHT" if dx > 0 else "NEEDS_LEFT")
        movement_mode = "SMOOTH_PULSE" if target_is_moving else "SMOOTH_FAST"

        # ------------------------------------------------------------------
        # BRANCH 1: PHYSICAL DISTANCE PATH PLANNING (When distance is measured)
        # ------------------------------------------------------------------
        if dist_cm is not None and target_dist_cm is not None and dist_cm > 0:
            dist_error = dist_cm - target_dist_cm

            # Scenario 1A: Over-extended past target standoff (closer than threshold!)
            if dist_error < -4.0:
                damping = 0.85
                adjusted_pwm = max(self.min_overcoming_pwm, min(self.max_speed, round(self.base_speed * damping)))
                arm_plan = self._compute_arm_plan("NUDGE_BACK", category, box_w, sw, area_ratio, is_centered)
                return VLMMotionPlan(
                    action="NUDGE_BACK",
                    recommended_pwm=adjusted_pwm,
                    duration_ms=self.nudge_default_ms,
                    damping_factor=damping,
                    base_speed=self.base_speed,
                    overshoot_risk="HIGH",
                    stiction_risk="LOW",
                    alignment_status=align_status,
                    target_is_moving=target_is_moving,
                    movement_mode="SMOOTH_PULSE",
                    left_pwm=-adjusted_pwm,
                    right_pwm=-adjusted_pwm,
                    path_type="REVERSE_CLEAR",
                    is_overextended=True,
                    continuous_drive=False,
                    distance_cm=dist_cm,
                    target_dist_cm=target_dist_cm,
                    horizontal_error_px=dx,
                    area_ratio=area_ratio,
                    target_info=target_info,
                    arm_plan=arm_plan,
                    rationale=(
                        f"Over-extension detected: Target at {dist_cm:.1f}cm is closer than standoff threshold {target_dist_cm:.1f}cm. "
                        f"Executing controlled reverse clear at {adjusted_pwm} PWM to restore safety clearance."
                    ),
                    source="VLM_KINEMATIC"
                )

            # Scenario 1B: Standoff Goal Reached (within target window ±4cm)
            if abs(dist_error) <= 4.0:
                action_name = "ALIGNED_GRASP" if is_centered else "ALIGNED_HOLD"
                arm_plan = self._compute_arm_plan(action_name, category, box_w, sw, area_ratio, is_centered)
                return VLMMotionPlan(
                    action=action_name,
                    recommended_pwm=0,
                    duration_ms=0,
                    damping_factor=1.0,
                    base_speed=self.base_speed,
                    overshoot_risk="LOW",
                    stiction_risk="LOW",
                    alignment_status=align_status,
                    target_is_moving=target_is_moving,
                    movement_mode="STOP",
                    left_pwm=0,
                    right_pwm=0,
                    path_type="HOLD_STANDOFF",
                    is_overextended=False,
                    continuous_drive=False,
                    distance_cm=dist_cm,
                    target_dist_cm=target_dist_cm,
                    horizontal_error_px=dx,
                    area_ratio=area_ratio,
                    target_info=target_info,
                    arm_plan=arm_plan,
                    rationale=(
                        f"Target reached efficient standoff: Current {dist_cm:.1f}cm matches desired {target_dist_cm:.1f}cm (dx={dx:+d}px). "
                        f"Holding position smoothly without over-extending."
                    ),
                    source="VLM_KINEMATIC"
                )

            # Scenario 1C: Approaching Target along Efficient Continuous Path (dist_error > 4.0)
            if dist_error > 25.0:
                damping = 1.0
                adjusted_pwm = max(self.min_overcoming_pwm, min(self.max_speed, self.base_speed))
                overshoot_risk = "LOW"
            else:
                damping = max(0.65, min(1.0, dist_error / 25.0))
                adjusted_pwm = max(self.min_overcoming_pwm, min(self.max_speed, round(self.base_speed * damping)))
                overshoot_risk = "MEDIUM"

            turn_dir = "RIGHT" if dx > 0 else "LEFT"
            if is_centered:
                action_name = "DRIVE_FORWARD" if dist_error > 15.0 else "NUDGE_FORWARD"
                arm_plan = self._compute_arm_plan(action_name, category, box_w, sw, area_ratio, is_centered)
                return VLMMotionPlan(
                    action=action_name,
                    recommended_pwm=adjusted_pwm,
                    duration_ms=250,
                    damping_factor=damping,
                    base_speed=self.base_speed,
                    overshoot_risk=overshoot_risk,
                    stiction_risk="LOW",
                    alignment_status=align_status,
                    target_is_moving=target_is_moving,
                    movement_mode=movement_mode,
                    left_pwm=adjusted_pwm,
                    right_pwm=adjusted_pwm,
                    path_type="CONTINUOUS_APPROACH",
                    is_overextended=False,
                    continuous_drive=True,
                    distance_cm=dist_cm,
                    target_dist_cm=target_dist_cm,
                    horizontal_error_px=dx,
                    area_ratio=area_ratio,
                    target_info=target_info,
                    arm_plan=arm_plan,
                    rationale=(
                        f"Continuous approach: Target at {dist_cm:.1f}cm (error {dist_error:+.1f}cm) moving smoothly at {adjusted_pwm} PWM "
                        f"(damping {damping:.2f}) without over-extending."
                    ),
                    source="VLM_KINEMATIC"
                )
            elif abs(dx) <= self.pulse_threshold_px or dist_error > 15.0:
                # Continuous Arc Steering Path
                steer_bias = int(min(25, (abs(dx) / 100.0) * 30))
                if dx > 0:
                    l_cmd = min(self.max_speed, adjusted_pwm + steer_bias)
                    r_cmd = max(self.min_overcoming_pwm - 15, adjusted_pwm - steer_bias * 2)
                    action_name = "TURN_RIGHT"
                else:
                    r_cmd = min(self.max_speed, adjusted_pwm + steer_bias)
                    l_cmd = max(self.min_overcoming_pwm - 15, adjusted_pwm - steer_bias * 2)
                    action_name = "TURN_LEFT"

                arm_plan = self._compute_arm_plan(action_name, category, box_w, sw, area_ratio, is_centered)
                return VLMMotionPlan(
                    action=action_name,
                    recommended_pwm=max(l_cmd, r_cmd),
                    duration_ms=180,
                    damping_factor=damping,
                    base_speed=self.base_speed,
                    overshoot_risk=overshoot_risk,
                    stiction_risk="LOW",
                    alignment_status=align_status,
                    target_is_moving=target_is_moving,
                    movement_mode=movement_mode,
                    left_pwm=l_cmd,
                    right_pwm=r_cmd,
                    path_type="ARC_ALIGN",
                    is_overextended=False,
                    continuous_drive=True,
                    distance_cm=dist_cm,
                    target_dist_cm=target_dist_cm,
                    horizontal_error_px=dx,
                    area_ratio=area_ratio,
                    target_info=target_info,
                    arm_plan=arm_plan,
                    rationale=(
                        f"Continuous arc path {turn_dir.lower()}: dx={dx:+d}px, dist={dist_cm:.1f}cm. "
                        f"Differential drive ({l_cmd}/{r_cmd} PWM) curves toward target smoothly."
                    ),
                    source="VLM_KINEMATIC"
                )
            else:
                turn_pwm = max(self.min_overcoming_pwm, min(self.max_speed, self.turn_speed))
                action_name = f"PIVOT_{turn_dir}"
                l_cmd = turn_pwm if dx > 0 else -turn_pwm
                r_cmd = -turn_pwm if dx > 0 else turn_pwm
                arm_plan = self._compute_arm_plan(action_name, category, box_w, sw, area_ratio, is_centered)
                return VLMMotionPlan(
                    action=action_name,
                    recommended_pwm=turn_pwm,
                    duration_ms=180,
                    damping_factor=1.0,
                    base_speed=self.base_speed,
                    overshoot_risk="MEDIUM",
                    stiction_risk="LOW",
                    alignment_status=align_status,
                    target_is_moving=target_is_moving,
                    movement_mode=movement_mode,
                    left_pwm=l_cmd,
                    right_pwm=r_cmd,
                    path_type="PIVOT_ALIGN",
                    is_overextended=False,
                    continuous_drive=False,
                    distance_cm=dist_cm,
                    target_dist_cm=target_dist_cm,
                    horizontal_error_px=dx,
                    area_ratio=area_ratio,
                    target_info=target_info,
                    arm_plan=arm_plan,
                    rationale=(
                        f"Large heading offset (dx={dx:+d}px) at close range ({dist_cm:.1f}cm). Controlled pivot in place."
                    ),
                    source="VLM_KINEMATIC"
                )

        # ------------------------------------------------------------------
        # BRANCH 2: SWEET-SPOT AREA RATIO PATH PLANNING (Unit test & camera fallback)
        # ------------------------------------------------------------------
        # Scenario 1: Already inside sweet-spot zone (Ready for Servo Arm Grasp)
        if is_centered and (0.85 <= area_ratio <= 1.18):
            arm_plan = self._compute_arm_plan("ALIGNED_GRASP", category, box_w, sw, area_ratio, is_centered)
            grip_target = arm_plan["calibrated_angles"]["grip_target"]
            return VLMMotionPlan(
                action="ALIGNED_GRASP",
                recommended_pwm=0,
                duration_ms=0,
                damping_factor=1.0,
                base_speed=self.base_speed,
                overshoot_risk="LOW",
                stiction_risk="LOW",
                alignment_status=align_status,
                target_is_moving=target_is_moving,
                movement_mode="STOP",
                left_pwm=0,
                right_pwm=0,
                path_type="HOLD_STANDOFF",
                is_overextended=False,
                continuous_drive=False,
                horizontal_error_px=dx,
                area_ratio=area_ratio,
                target_info=target_info,
                arm_plan=arm_plan,
                rationale=(
                    f"Target {category} is fully aligned in X (dx={dx:+d}px) and area ratio is {area_ratio*100:.1f}%. "
                    f"Servo arm grab planned per robot config: Lower S1({self.s1_down}°) & S2({self.s2_down}°), "
                    f"clamp S3({grip_target}°), and lift to stow (S1:{self.s1_stow}°, S2:{self.s2_stow}°)."
                ),
                source="VLM_KINEMATIC"
            )

        # Scenario 2: Overshot target (too close / behind grasp threshold)
        if is_centered and (area_ratio > 1.18):
            damping = 0.85
            adjusted_pwm = max(self.min_overcoming_pwm, min(self.max_speed, round(self.base_speed * damping)))
            arm_plan = self._compute_arm_plan("NUDGE_BACK", category, box_w, sw, area_ratio, is_centered)
            return VLMMotionPlan(
                action="NUDGE_BACK",
                recommended_pwm=adjusted_pwm,
                duration_ms=self.nudge_default_ms,
                damping_factor=damping,
                base_speed=self.base_speed,
                overshoot_risk="HIGH",
                stiction_risk="LOW",
                alignment_status=align_status,
                target_is_moving=target_is_moving,
                movement_mode="SMOOTH_PULSE",
                left_pwm=-adjusted_pwm,
                right_pwm=-adjusted_pwm,
                path_type="REVERSE_CLEAR",
                is_overextended=True,
                continuous_drive=False,
                horizontal_error_px=dx,
                area_ratio=area_ratio,
                target_info=target_info,
                arm_plan=arm_plan,
                rationale=(
                    f"Overshoot detected: Target area ratio is {area_ratio*100:.1f}% (>118%). "
                    f"Executing gentle {self.nudge_default_ms}ms reverse nudge at {adjusted_pwm} PWM "
                    f"(scaled from baseline {self.base_speed} PWM) to restore clearance."
                ),
                source="VLM_KINEMATIC"
            )

        # Scenario 3: Horizontal Misalignment Correction
        if not is_centered:
            turn_dir = "RIGHT" if dx > 0 else "LEFT"
            if abs(dx) <= self.pulse_threshold_px:
                action_name = f"NUDGE_{turn_dir}"
                duration = max(50, min(120, int(self.nudge_default_ms * (abs(dx) / self.align_tol_x))))
                adjusted_pwm = max(self.min_overcoming_pwm, min(self.max_speed, self.nudge_pwm))
                arm_plan = self._compute_arm_plan(action_name, category, box_w, sw, area_ratio, is_centered)
                l_cmd = adjusted_pwm if dx > 0 else -adjusted_pwm
                r_cmd = -adjusted_pwm if dx > 0 else adjusted_pwm
                return VLMMotionPlan(
                    action=action_name,
                    recommended_pwm=adjusted_pwm,
                    duration_ms=duration,
                    damping_factor=0.8,
                    base_speed=self.base_speed,
                    overshoot_risk="LOW",
                    stiction_risk="LOW",
                    alignment_status=align_status,
                    target_is_moving=target_is_moving,
                    movement_mode=movement_mode,
                    left_pwm=l_cmd,
                    right_pwm=r_cmd,
                    path_type="FINE_ALIGN",
                    is_overextended=False,
                    continuous_drive=False,
                    horizontal_error_px=dx,
                    area_ratio=area_ratio,
                    target_info=target_info,
                    arm_plan=arm_plan,
                    rationale=(
                        f"Fine alignment needed: dx={dx:+d}px. Anti-stiction pulse of {duration}ms "
                        f"at {adjusted_pwm} PWM (baseline {self.base_speed} PWM) prevents motor deadband stall while eliminating turning overshoot."
                    ),
                    source="VLM_KINEMATIC"
                )
            else:
                action_name = f"PIVOT_{turn_dir}"
                turn_pwm = max(self.min_overcoming_pwm, min(self.max_speed, self.turn_speed))
                arm_plan = self._compute_arm_plan(action_name, category, box_w, sw, area_ratio, is_centered)
                l_cmd = turn_pwm if dx > 0 else -turn_pwm
                r_cmd = -turn_pwm if dx > 0 else turn_pwm
                return VLMMotionPlan(
                    action=action_name,
                    recommended_pwm=turn_pwm,
                    duration_ms=180,
                    damping_factor=1.0,
                    base_speed=self.base_speed,
                    overshoot_risk="MEDIUM",
                    stiction_risk="LOW",
                    alignment_status=align_status,
                    target_is_moving=target_is_moving,
                    movement_mode=movement_mode,
                    left_pwm=l_cmd,
                    right_pwm=r_cmd,
                    path_type="PIVOT_ALIGN",
                    is_overextended=False,
                    continuous_drive=False,
                    horizontal_error_px=dx,
                    area_ratio=area_ratio,
                    target_info=target_info,
                    arm_plan=arm_plan,
                    rationale=(
                        f"Large horizontal offset (dx={dx:+d}px). Controlled pivot turn {turn_dir.lower()} "
                        f"at {turn_pwm} PWM (baseline {self.base_speed} PWM) to face the {category} directly."
                    ),
                    source="VLM_KINEMATIC"
                )

        # Scenario 4: Centered, approaching target forward
        if area_ratio < 0.60:
            adjusted_pwm = max(self.min_overcoming_pwm, min(self.max_speed, self.base_speed))
            arm_plan = self._compute_arm_plan("DRIVE_FORWARD", category, box_w, sw, area_ratio, is_centered)
            dyn_text = "in motion. Smooth continuous arc cruise" if target_is_moving else "stationary and centered. Fast smooth continuous approach without frame pauses"
            return VLMMotionPlan(
                action="DRIVE_FORWARD",
                recommended_pwm=adjusted_pwm,
                duration_ms=250,
                damping_factor=1.0,
                base_speed=self.base_speed,
                overshoot_risk="LOW",
                stiction_risk="LOW",
                alignment_status=align_status,
                target_is_moving=target_is_moving,
                movement_mode=movement_mode,
                left_pwm=adjusted_pwm,
                right_pwm=adjusted_pwm,
                path_type="CONTINUOUS_APPROACH",
                is_overextended=False,
                continuous_drive=True,
                horizontal_error_px=dx,
                area_ratio=area_ratio,
                target_info=target_info,
                arm_plan=arm_plan,
                rationale=(
                    f"Target {category} is {dyn_text} ({area_ratio*100:.1f}% sweet area) at {adjusted_pwm} PWM."
                ),
                source="VLM_KINEMATIC"
            )
        else:
            # Near target (60% to 85% area): Apply Anti-Overshoot Damping!
            damping = max(0.6, 1.0 - (area_ratio - 0.60) * 1.5)
            adjusted_pwm = max(self.min_overcoming_pwm, min(self.max_speed, round(self.base_speed * damping)))
            duration = max(50, min(self.nudge_default_ms, int(self.nudge_default_ms * damping)))
            arm_plan = self._compute_arm_plan("NUDGE_FORWARD", category, box_w, sw, area_ratio, is_centered)
            dyn_text = "moving target - continuous decelerating track" if target_is_moving else "stationary target - fast smooth braking approach"
            return VLMMotionPlan(
                action="NUDGE_FORWARD",
                recommended_pwm=adjusted_pwm,
                duration_ms=duration,
                damping_factor=damping,
                base_speed=self.base_speed,
                overshoot_risk="MEDIUM",
                stiction_risk="LOW",
                alignment_status=align_status,
                target_is_moving=target_is_moving,
                movement_mode=movement_mode,
                left_pwm=adjusted_pwm,
                right_pwm=adjusted_pwm,
                path_type="CONTINUOUS_APPROACH",
                is_overextended=False,
                continuous_drive=True,
                horizontal_error_px=dx,
                area_ratio=area_ratio,
                target_info=target_info,
                arm_plan=arm_plan,
                rationale=(
                    f"Anti-overshoot braking active ({dyn_text}): Target is {area_ratio*100:.1f}% of sweet area. "
                    f"Damped {duration}ms forward pulse at {adjusted_pwm} PWM (scaled by {damping:.2f}x from baseline {self.base_speed} PWM) "
                    f"ensures steady advance without overrun."
                ),
                source="VLM_KINEMATIC"
            )

    def _query_vlm_reasoner(
        self,
        detection: DetectionResult,
        dx: int,
        area_ratio: float,
        mask_pts_count: int,
        sweet_spot: dict,
        kinematic_baseline: VLMMotionPlan,
        timeout_s: float
    ) -> Optional[VLMMotionPlan]:
        """Queries local Ollama VLM with concise structured context to enrich physical rationale."""
        prompt = (
            f"You are the motion and arm manipulation planner for the ErovoutikaGrab robot.\n"
            f"Vision Model: YOLOE. Target: {detection.category} (conf {detection.confidence:.2f}, {detection.material_color}).\n"
            f"Metrics: dx={dx:+d}px (Set-point tolerance +/-{self.align_tol_x}px), "
            f"Area Ratio={area_ratio*100:.1f}%, Seg Contour={mask_pts_count} pts.\n"
            f"Chassis Motion: {kinematic_baseline.action}, PWM={kinematic_baseline.recommended_pwm}, Duration={kinematic_baseline.duration_ms}ms.\n"
            f"Servo Arm Plan: Action={kinematic_baseline.arm_plan.get('arm_action', 'HOLD')} "
            f"(S1={self.s1_stow}°->{self.s1_down}°, S2={self.s2_stow}°->{self.s2_down}°, "
            f"S3={self.s3_open}°->{kinematic_baseline.arm_plan.get('calibrated_angles', {}).get('grip_target', self.s3_close)}°).\n"
            f"Provide a 1-sentence engineering confirmation why this coordinated motion and servo arm grab plan avoids overshoot and ensures secure manipulation."
        )

        payload = {
            "model": self.vlm_model,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": 0.2,
                "num_predict": 40
            }
        }

        req = urllib.request.Request(
            f"{self.ollama_url}/api/generate",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"}
        )

        with urllib.request.urlopen(req, timeout=timeout_s) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            vlm_text = data.get("response", "").strip()
            if vlm_text:
                # Merge VLM confirmation into rationale
                kinematic_baseline.rationale = f"{kinematic_baseline.rationale} [VLM Advisory: {vlm_text}]"
                kinematic_baseline.source = "VLM_OLLAMA"
                return kinematic_baseline

        return None

    def get_last_plan(self) -> Optional[VLMMotionPlan]:
        with self._lock:
            return self._last_plan

    def record_feedback(
        self,
        action_taken: str,
        pwm: int,
        duration_ms: int,
        prev_dx: int,
        new_dx: int,
        target_name: str = "target",
        area_ratio: float = 0.0
    ) -> Dict[str, Any]:
        """Records physical pulse outcome, detects stiction stall or overshoot, and adapts planner parameters in real time."""
        with self._lock:
            self.total_plans_executed += 1
            prev_err = abs(prev_dx)
            new_err = abs(new_dx)
            delta_err = prev_err - new_err

            outcome = "PROGRESS"
            notes = ""

            # Check for overshoot (error crossed zero and flipped sign by significant margin)
            is_overshoot = (prev_dx > 15 and new_dx < -15) or (prev_dx < -15 and new_dx > 15)
            # Check for stiction stall (error did not change despite motor pulse)
            is_stall = (abs(delta_err) <= 3) and (prev_err > self.align_tol_x)

            if is_overshoot:
                outcome = "OVERSHOOT_DETECTED"
                self.overshoots_prevented += 1
                # Adapt: increase damping (lower speed/duration)
                self.adaptive_damping_scale = max(0.65, round(self.adaptive_damping_scale * 0.88, 3))
                self.pulse_duration_scale = max(0.65, round(self.pulse_duration_scale * 0.90, 3))
                notes = f"Overshoot from {prev_dx:+d}px to {new_dx:+d}px. Damping increased to {self.adaptive_damping_scale:.2f}x."
            elif is_stall:
                outcome = "STICTION_STALL_DETECTED"
                self.stiction_recoveries += 1
                # Adapt: boost overcoming PWM and slightly lengthen pulse
                self.adaptive_stiction_boost = min(15, self.adaptive_stiction_boost + 2)
                self.pulse_duration_scale = min(1.30, round(self.pulse_duration_scale * 1.05, 3))
                notes = f"Stall at {prev_dx:+d}px. Stiction boost increased to +{self.adaptive_stiction_boost} PWM."
            else:
                # Steady progress: gradually decay stiction boost back to baseline
                if self.adaptive_stiction_boost > 0 and self.total_plans_executed % 3 == 0:
                    self.adaptive_stiction_boost -= 1
                notes = f"Aligned error reduced by {delta_err}px ({prev_dx:+d} -> {new_dx:+d}px)."

            log_entry = {
                "timestamp": time.time(),
                "time_str": time.strftime("%Y-%m-%d %H:%M:%S"),
                "target": target_name,
                "action": action_taken,
                "pwm": pwm,
                "duration_ms": duration_ms,
                "prev_dx": prev_dx,
                "new_dx": new_dx,
                "delta_dx": delta_err,
                "area_ratio": round(area_ratio, 3),
                "outcome": outcome,
                "notes": notes,
                "stiction_boost": self.adaptive_stiction_boost,
                "damping_scale": round(self.adaptive_damping_scale, 2),
                "pulse_scale": round(self.pulse_duration_scale, 2),
            }

            self.recent_history.append(log_entry)
            if len(self.recent_history) > 100:
                self.recent_history.pop(0)

            # Persist to disk log
            try:
                os.makedirs(os.path.dirname(self.adaptation_log_path), exist_ok=True)
                with open(self.adaptation_log_path, "a", encoding="utf-8") as f:
                    f.write(json.dumps(log_entry) + "\n")
            except Exception as e:
                logger.warning(f"Failed to append VLM adaptation log: {e}")

            return log_entry

    def get_adaptation_stats(self) -> Dict[str, Any]:
        """Returns runtime learning metrics and recent history."""
        with self._lock:
            return {
                "total_plans_generated": self.total_plans_generated,
                "total_plans_executed": self.total_plans_executed,
                "overshoots_prevented": self.overshoots_prevented,
                "stiction_recoveries": self.stiction_recoveries,
                "stiction_boost_pwm": self.adaptive_stiction_boost,
                "damping_scale": round(self.adaptive_damping_scale, 2),
                "pulse_duration_scale": round(self.pulse_duration_scale, 2),
                "recent_history": list(self.recent_history[-20:])
            }
